name: package-hterm


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install terser
      run: npm install terser -g

    - name: Clone hterm
      run: |
        git clone https://chromium.googlesource.com/apps/libapps
        cd libapps
        # Tue Dec 29 2020
        git checkout 71452719967c3930a4cf5b15335e2bc42b7206ae

    - name: Concat JS files to hterm_all.js
      run: |
        cd libapps
        git log -n 10 --oneline hterm
        cd hterm
        ./bin/mkdist*

    - name: Replace const lib with var.
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "const lib = {};"
        replace: "var lib = {};"
        include: "hterm_all.js"

    - name: Replace const hterm with var.
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "const hterm = {};"
        replace: "var hterm = {};"
        include: "hterm_all.js"

    - name: Minify JS
      run: |
        cd libapps/hterm/dist/js/
        terser --compress --mangle --comments `false` -- hterm_all.js > hterm_all.min.js

    - uses: actions/upload-artifact@v2
      with:
        name: hterm-artifacts
        path: libapps/hterm/dist/js/hterm_all.*
